CREATE TABLE IF NOT EXISTS security_scans (
  id             varchar(64)  NOT NULL,
  tenant_id      varchar(64)  NOT NULL,
  triggered_at   datetime(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  tool           varchar(32)  NOT NULL,
  target         text,
  image          text,
  status         varchar(16)  NOT NULL,
  critical       int NOT NULL DEFAULT 0,
  high           int NOT NULL DEFAULT 0,
  medium         int NOT NULL DEFAULT 0,
  low            int NOT NULL DEFAULT 0,
  findings_total int NOT NULL DEFAULT 0,
  artifact_url   text,
  raw_format     varchar(16),
  duration_ms    bigint,
  source         varchar(32),
  commit_sha     varchar(64),
  branch         varchar(64),
  PRIMARY KEY (id),
  KEY idx_tenant_dt (tenant_id, triggered_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
